#!/usr/bin/env bash

set -e

CONFIG="install.conf.yaml"

BASEDIR=$(pwd)
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DOTBOT_DIR="${SCRIPT_DIR}/dotbot"
DOTBOT_BIN="bin/dotbot"

pushd "${SCRIPT_DIR}" > /dev/null
    git submodule update --init --recursive "${DOTBOT_DIR}"
popd > /dev/null

"${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${SCRIPT_DIR}" -c "${SCRIPT_DIR}/${CONFIG}" "${@}"
